  name: Build ChoEazyFirewall

  on:
    push:
      branches:
        - master
    pull_request:
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: 21

        - name: Grant execute permission for gradlew
          run: chmod +x ./gradlew

        - name: Build plugin JAR
          run: ./gradlew clean build

        - name: Upload plugin JAR artifact
          uses: actions/upload-artifact@v4
          with:
            name: ChoEazyFirewall
            path: build/libs/*.jar