name: Build ChoEazyFirewall

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build plugin JAR
      run: ./gradlew clean build

    - name: Upload plugin JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: choeazyfirewall-jar
        path: build/libs/*.jar
